---
module: "Achievo"
package: "com.timetrack"
checkpoints:
  setup: true
  model: true
  features:
    sorted: true
    sorting:
    - "1-user-management"
    - "2-customer-management"
    - "3-cost-center-management"
    userManagement:
      anAdminCreatesANewUser:
        action: true
        actionClassName: "CreateNewUserByAdmin"
        aUserMustHaveAValidEmailAddress:
          glue: true
          service: true
          done: true
        aUsersMustHaveAFirstAndLastName:
          glue: true
          service: true
          done: true
        aUserCannotBeCreatedIfAnotherUserWithTheSameEmailAddressExists:
          glue: true
          service: true
          done: true
        done: true
      anAdminFetchesAListOfAllUsers:
        action: true
        actionClassName: "FetchAllUsersWithActiveFilter"
        theAdminCanFetchAListOfAllUsers:
          glue: true
          service: true
          done: true
        theAdminCanFilterTheListByActive/inactive:
          glue: true
          service: true
          done: true
        theAdminReceivesAnEmptyListIfThereAreNoUsers:
          glue: true
          service: true
          done: true
        done: true
      anAdminFetchesASingleUserByEmail:
        action: true
        actionClassName: "FindUserByEmail"
        theAdminCanShouldFindAnExistingUser:
          glue: true
          service: true
          done: true
        ifAUserDoesNotExist,AnErrorShouldOccur:
          glue: true
          service: true
