---
module: "Achievo"
package: "com.timetrack"
checkpoints:
  setup: true
  model: true
  features:
    sorted: true
    sorting:
    - "1-user-management"
    - "2-customer-management"
    - "3-cost-center-management"
    userManagement:
      anAdminCreatesANewUser:
        action: true
        actionClassName: "CreateNewUserByAdmin"
        aUserMustHaveAValidEmailAddress:
          glue: true
          service: true
          done: true
        aUsersMustHaveAFirstAndLastName:
          glue: true
          service: true
          done: true
        aUserCannotBeCreatedIfAnotherUserWithTheSameEmailAddressExists:
          glue: true
          service: true
          done: true
        done: true
      anAdminFetchesAListOfAllUsers:
        action: true
        actionClassName: "FetchAllUsersWithActiveFilter"
        theAdminCanFetchAListOfAllUsers:
          glue: true
          service: true
          done: true
        theAdminCanFilterTheListByActive/inactive:
          glue: true
          service: true
          done: true
        theAdminReceivesAnEmptyListIfThereAreNoUsers:
          glue: true
          service: true
          done: true
        done: true
      anAdminFetchesASingleUserByEmail:
        action: true
        actionClassName: "FindUserByEmail"
        theAdminCanShouldFindAnExistingUser:
          glue: true
          service: true
          done: true
        ifAUserDoesNotExist,AnErrorShouldOccur:
          glue: true
          service: true
          done: true
        done: true
      anAdminModifiesAUser:
        action: true
        actionClassName: "ModifyExistingUserByAdmin"
        theAdminCanModifyAllFieldsOfAUser:
          glue: true
          service: true
          done: true
        ifAUserDoesNotExist,AnErrorShouldOccur:
          glue: true
          service: true
          done: true
        done: true
      done: true
    customerManagement:
      aControllerCreatesANewCustomer:
        action: true
        actionClassName: "CreateNewCustomerWithRequiredInformation"
        customerMustHaveAName,ContactEmail,PhoneNumberAndBillingAddress:
          glue: true
          service: true
          done: true
        customerMustHaveAValidContactEmail:
          glue: true
          service: true
          done: true
        customerMustHaveAValidPhoneNumber:
          glue: true
          service: true
          done: true
        done: true
      aControllerModifiesACustomer:
        action: true
        actionClassName: "ModifyExistingCustomerDetails"
        theControllerCanModifyAllFieldsOfACustomer:
          glue: true
          service: true
          done: true
        ifACustomerDoesNotExist,AnErrorOccurs:
          glue: true
          service: true
          done: true
        done: true
      aControllerViewsAListOfAllCustomers:
        action: true
        actionClassName: "FetchFilterableListOfAllCustomers"
        theControllerCanFetchAListOfAllCustomers:
          glue: true
          service: true
          done: true
        theControllerCanFilterTheListByProvidingPartOfTheCustomerName:
          glue: true
          service: true
          done: true
        theControllerReceivesAnEmptyListIfThereAreNoCustomers:
          glue: true
          service: true
          done: true
        done: true
      done: true
    costManagement:
      aControllerCreatesACostCenter:
        action: true
        actionClassName: "CreateCostCenterWithNameAndManager"
        aCostCenterMustHaveANameAndAManager:
          glue: true
          service: true
          done: true
        aCostCenterIsActiveByDefault:
          glue: true
          service: true
          done: true
        done: true
      aControllerViewsAListOfAllCostCenters:
        action: true
        actionClassName: "FetchAndFilterCostCenters"
        theControllerCanFetchAListOfAllCostCenters:
          glue: true
          service: true
          done: true
        theControllerReceivesAnEmptyListIfThereAreNoCostCenters:
          glue: true
          service: true
          done: true
